export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS';
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';
export const TOGGLE_SELECT_USER = 'TOGGLE_SELECT_USER';
export const UPDATED_USER_SUCCESS = 'UPDATED_USER_SUCCESS';
export const REMOVE_USER_SUCCESS = 'REMOVE_USER_SUCCESS';

export const FETCH_PROFILES_SUCCESS = 'FETCH_PROFILES_SUCCESS';
export const CREATE_PROFILE_SUCCESS = 'CREATE_PROFILE_SUCCESS';

export const CREATE_WALLET_SUCCESS = 'CREATE_WALLET_SUCCESS';
export const RESTORE_WALLET_SUCCESS = 'RESTORE_WALLET_SUCCESS';
export const FETCH_WALLETS_SUCCESS = 'FETCH_WALLETS_SUCCESS';
export const REMOVE_WALLET_SUCCESS = 'REMOVE_WALLET_SUCCESS';
export const FETCH_WALLET_SUCCESS = 'FETCH_WALLET_SUCCESS';
export const UPDATED_WALLET_SUCCESS = 'UPDATED_WALLET_SUCCESS';
export const TOGGLE_SELECT_WALLET = 'TOGGLE_SELECT_WALLET';

export const CREATE_AIRDROP_SUCCESS = 'CREATE_AIRDROP_SUCCESS';
export const CREATE_TRANSACTION_SUCCESS = 'CREATE_TRANSACTION_SUCCESS';
export const MINT_NFT_SUCCESS = 'MINT_NFT_SUCCESS';
export const FETCH_TRANSACTION_SUCCESS = 'FETCH_TRANSACTION_SUCCESS';
export const CREATE_MINT_SUCCESS = 'CREATE_MINT_SUCCESS';

export const FETCH_ITEMS_SUCCESS = 'FETCH_ITEMS_SUCCESS';
export const CREATE_ITEM_SUCCESS = 'CREATE_ITEMS_SUCCESS';
