export type { NearTransactionSignature, NearConnectionConfig } from '@mindblox-wallet-adapter/base';
export { NearPublicKey, NearTransaction, NearConnection, NearKeypair } from '@mindblox-wallet-adapter/base';
export type {
    SendNear,
    NearAccount,
    NearWallet,
    ContractWithMint as NearContractWithMint,
    ConnectionContextState as NearConnectionContextState,
    MintNft as MintNearNft,
    WalletContextState as NearWalletContextState,
    ENDPOINT_NAME as NEAR_ENDPOINT_NAME,
    NftMetaData as NearNftMetaData,
    BrowserWalletConfig as NearBrowserWalletConfig,
    Gas as NearGas,
    Config as NearConfig,
    MintNft as NearMintNft,
} from '@mindblox-wallet-adapter/near';
export {
    walletName as nearWalletName,
    ENDPOINTS as NEAR_ENDPOINTS,
    WalletContext as NearWalletContext,
    ConnectionContext as NearConnectionContext,
    ConnectionProvider as NearConnectionProvider,
    BrowserWalletAdapterConfig as NearBrowserWalletAdapterConfig,
    BrowserWalletAdapter as NearBrowserWalletAdapter,
    WalletAdapterNetwork as NearWalletAdapterNetwork,
    useConnection as useNearConnection,
    getAccount as getNearAccount,
    getImplicitAccountId as getNearImplicitAccountId,
    getBalance as getNearBalance,
    getKeyPairFromPrivateKey as getNearKeyPairFromPrivateKey,
    getKeyPairFromSeedPhrase as getNearKeyPairFromSeedPhrase,
    getNativeKeyPairFromPrivateKey as getNearNativeKeyPairFromPrivateKey,
    getPublicKey as getNearPublicKey,
    mintNft as mintNearNft,
    sendFundsTransaction as sendNearFundsTransaction,
    signAndSendTransaction as signAndSendNearTransaction,
    sendTransaction as sendNearTransaction,
    getTransactionStatus as getNearTransactionStatus,
    useBrowserWallet as useNearBrowserWallet,
    useWallet as useNearWallet,
    BrowserWalletProvider as NearBrowserWalletProvider,
    getNetworkConfig as getNearNetworkConfig,
    isValidAccount as isValidNearAccount,
    isValidName as isValidNearName,
    getNetwork as getNearNetwork,
    getImplicitId as getNearImplicitId,
    isImplicitAddress as isNearImplicitAddress,
    KeyType as NearKeyType,
    generateSeedPhrase as generateNearSeedPhrase,
    normalizeSeedPhrase as normalizeNearSeedPhrase,
    parseSeedPhrase as parseNearSeedPhrase,
    findSeedPhraseKey as findNearSeedPhraseKey,
    getSign as getNearSign,
    SCHEMA as NEAR_SCHEMA,
    BrowserWallet as NearBrowserWallet,
    toArray as toNearConfigArray,
    config as nearDefaultConfig,
    generateNearKeys,
    getImplicitIdsFromName as getImplicitNearIdsFromName,
    getFiat as getNearFiat,
} from '@mindblox-wallet-adapter/near';
